services:
    dzangocart.store_listener:
        class: Dzangocart\Bundle\CoreBundle\EventListener\StoreListener      
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onFilterController, priority: -256 }
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
