services:
    twig.extension.dzangocart:
        class: Dzangocart\Bundle\CoreBundle\Twig\Extension\DzangocartExtension
        tags:
            - { name: twig.extension }

    twig.extension.address:
        class: Dzangocart\Bundle\CoreBundle\Twig\Extension\AddressExtension
        tags:
            - { name: twig.extension }
