services:
    twig.extension.dzangocart:
        class: Dzangocart\Bundle\CoreBundle\Twig\Extension\DzangocartExtension
        arguments: [@service_container]
        tags:
            - { name: twig.extension }
